### PR TITLE
Fix a few typos to allow for some builds to work

### PR DESCRIPTION
**Pull request by afroraydude**

### CODE REVIEW

**Review by dslm4515 — APPROVED** [review]
Good catch!
Thanks!

**Comment by afroraydude** [comment]
No problem and thank you for this project! Been using it to make a distro for myself.

**Comment by dslm4515** [comment]
@afroraydude Really? Wow.

I originally chose to upload my work as I got tired of remembering what flash drive my work was on... It took me months to figure out the work flow to get the tool chains to recognize musl and during that time I almost lost all of it since it was on a single flash drive.

**Comment by afroraydude** [comment]
@dslm4515 heh definitely been there with less important projects.

**Pull request merged**
