### PR TITLE
Remove unnecessary flags passed to GCC configure scripts

### PR DESCRIPTION
**Pull request by firasuke**
I removed some unnecessary flags that were being passed to GCC's configure scripts. These flags are already enabled by default:

* `--enable-c99` is enabled by default (check libstdc++-v3 configure script)
* `--enable-long-long` is enabled by default (check libstdc++-v3 configure script)
* `--enable-checking=release` is enabled by default when GCC is being built from a release tarball (check https://gcc.gnu.org/install/configure.html)
* `--enable-shared` is enabled by default
* `--enable-lto` is enabled by default (check GCC configure script)

### CODE REVIEW

**Comment by firasuke** [comment]
To answer your question in a previous (now closed) pull request, yes [glaucus](https://github.com/firasuke/glaucus) uses the latest s6-rc and not the old 0.4 version.

**Comment by dslm4515** [comment]
Thanks!
I do appreciate your contributions here!

@firasuke , I was looking at your project glaucus, but had trouble finding the bootscripts used for s6+s6-rc. I would like to update my bootscripts to work on the latest s6+s6-rc

**Comment by firasuke** [comment]
You're most welcome!

Ah silly me, I totally forgot that I moved all s6 related stuff into a separate repository. Here you go [glaucus-s6-boot-scripts](https://github.com/firasuke/glaucus-s6-boot-scripts).

**Comment by dslm4515** [comment]
@firasuke I'm working on a i686 build. I did use your GCC patch from glaucus for AMD64 builds. I couldn't remember if you had a similar patch for ix86 (32-bit). In fact, I only see a patch for GCC for AMD64. I remembered there were patches for other CPU architecture. Where'd they go?

**Comment by firasuke** [comment]
> @firasuke I'm working on a i686 build. I did use your GCC patch from glaucus for AMD64 builds. I couldn't remember if you had a similar patch for ix86 (32-bit). In fact, I only see a patch for GCC for AMD64. I remembered there were patches for other CPU architecture. Where'd they go?

If you meant `x86` then the `x86-64` patch can be used for it as they both use `gcc/config/i386`. You can find all the patches from glaucus and for supported architectures in [`mussel`](https://github.com/firasuke/mussel/tree/main/patches/gcc/glaucus).

**Comment by dslm4515** [comment]
>If you meant `x86` then the `x86-64` patch can be used for it as they both use `gcc/config/i386`. 

Yes!. Thanks!

**Pull request merged**
